name: Windows Wheels

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2019]

    steps:
      - uses: actions/checkout@v3

      - name: Install Dependencies
        run: python -m pip install snappy pytest

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.15.0
        env:
          # Skip Python 3.12, and PyPy
          CIBW_SKIP: cp312-* pp*

      - name: Test build
        working-directory: dev
        run: pytest cython_test.py

      - uses: actions/upload-artifact@v3
        with:
          name: symplectic_windows_wheels
          path: ./wheelhouse/*.whl
